# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none
#relative_permalinks: true

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:               찬우의 이것저것
tagline:             "Chanwoo's blog"
description:         '자동차와 오토바이를 좋아하는 개발자 이것저것을 기록합니다.'
url:                 'https://blog.chanwookim.me'
baseurl:             ''

# About/contact
author:
  name:              Chanwoo Kim
  url:               https://chanwookim.me
  email:             chanwookim@me.com

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

google-analytics:
  id: "UA-130798210-1"

disqus:
  shortname: "chanwooo"

markdown: kramdown
kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
